title: "Bigfatbird - Der fette Vogel bricht den Ast"
url: https://bigfatbird.de
plugins:
  - jekyll-feed
collections:
    authors:
        output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
